grazen_system:
  ros__parameters:
    # Default map name (searched for in the 'maps' folder)
    default_map: "warehouse_map"
    
    # Default waypoints file (searched for in 'config' folder)
    default_waypoints: "waypoints.txt"